# Generated by Django 6.0.6 on 2026-07-19 20:15

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_category_options_category_level_category_lft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',), 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created_at',), 'verbose_name': 'کامنت ها', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='favoritpost',
            options={'ordering': ('-created_at',), 'verbose_name': ' لایک ها', 'verbose_name_plural': ' لایک ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'verbose_name': 'پست ', 'verbose_name_plural': 'پست '},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created_at',), 'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ('-created_at',), 'verbose_name': 'اشتراک کاربر', 'verbose_name_plural': 'اشتراک کاربر'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='posts.category', verbose_name='دسته بندی اصلی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='favoritpost',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='favoritpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to='posts.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='favoritpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='favoritpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='ویژه است'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='تیتر پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='ویدئو'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='limit_days',
            field=models.PositiveIntegerField(verbose_name='تعداد روز ها'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=255, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='روز پایان'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='روز شروع'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='posts.subscription', verbose_name='اشتراک'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
