# Generated by Django 6.0.6 on 2026-07-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_usersubscription'),
        ('users', '0002_remove_baseusermodel_email_alter_baseusermodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='posts.subscription'),
        ),
    ]
