# Generated by Django 6.0.6 on 2026-07-08 18:25

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofilemodel_subscription'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseusermodel',
            managers=[
                ('objects', users.models.BaseUserManager()),
            ],
        ),
    ]
