# Generated by Django 6.0.6 on 2026-07-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseusermodel_groups_baseusermodel_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='user',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
