# Generated by Django 6.0.6 on 2026-07-19 20:15

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_category_options_alter_comments_options_and_more'),
        ('users', '0006_remove_otpcode_user_otpcode_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseusermodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ('-created_at',), 'verbose_name': 'کد تایید ', 'verbose_name_plural': 'کد تایید '},
        ),
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربر'},
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='ادمین است'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='رمز ورود'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, verbose_name='شماره تلفن '),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام کاربری '),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name=' کد تایید'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='posts.subscription', verbose_name='اشتراک کاربر'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
