BBBBBBB BBBBBBBBBBB

BBBBB BBBBB

BBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX

XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
X

XXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
X

XXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXXX
    XXXXXXXXXXX
X

XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
X

XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX XXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

        XXXXXXXXX

        BB BBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXX
        BBBBB

        BB BBBBBBBBBB
            XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXX
            XXXXXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXX
            FFFF
        XXXXXX

        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    BB BBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXX
            X XXXXXX XXXX XXXXXXXXX
        XXXX
    BBBB BBB BBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXX
            XX XXX XX XXXXXXXXX
        XXXX
    BBBBB
    BBBBB

    XXXXXX

    XXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
    XXXXX

    BBB BBBBBBB BB BBBBBBBBBBBBBBBB

        XXXX XXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXX
                
            XXXXXX

            XXXXX
                
            XXXXXX

        XXXXXX

    BBBBB

        XXXXX XXXXXXXX XXXXXXXX

    BBBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXXXXXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

            BBBBBBBBBB

            

            XXXXXXX XXXXXXXXXXXXXX
                XXXXXX XXXXXXX
            XXXXXXXXX

        XXXXXXX

    XXXXXX

    BBBB

        XXX
            XXXXXX XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXX XX XXXXX X XXXXXXXX
        XXXX

    BBBBB

    XXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXX
    XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX

        BBB BBBB BB BBBBBBBBBBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXX

            BB BBBBBBBBBB
                XXXX XXXXXXX
            BBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXX

                XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBXX
                    XXXX XXXX X
                XXXX

            XXXXXX

        XXXXXX

        BBBBB

            XXXXX XXXXXXX XXXXXXXXXX

        BBBBBB

    XXXXXX

XXXXXX

BBBBBBBB