BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB


BBBBB BBBBBBBBB

            BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBB
            BBB BBBBBBBBBBBBBB BB BBBBBBBBBBB
             gettext(u'صفحه اصلی') 
             gettext(u'خروج') 
        
            BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBB
                
            BBBBBBBBBBBB

            BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBB
                
            BBBBBBBBBBBB
      
BBBBBBBB
