BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXXX XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX

    XXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXX
        XXXXXX X XXX XXXXXXXX XX X XXXXXXXXXXXX
    XXXX

    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB

        BBB BBBBB BB BBBB

            XXXX XXXXXXXXXXXXXXXXXXX

                XXXXXX XXXXXXX
                    
                XXXXXXXX

                

                BB BBBBBBBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                BBBBB

                BB BBBBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXXXX
                        FFFFFFF F
                    XXXXXXXX
                BBBBB

            XXXXXX

        BBBBBB

        XXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXX
        XXXXXXXXX

    XXXXXXX

XXXXXX

BBBBBBBB

BBBBB BBBBBBBBB

XXXXXXX

XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXX
X

XXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX
X

XXXXXXXXXXX XXXXXX
XXXXXXXXXXX XXXXXXX
XXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXX XXXXXXXXXXXX
XXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
X

XXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX

BBBBBBBB