BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXXXXX XXXXXX
BBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXX XX
    XXXXXXXXXXX
X

XXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
X

XXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXX XXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXX
    XXXXXXXXXXXXX
X

XXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXX
X

XXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
X
XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX

    XXX
        XXXXX XXXXX X
        
    XXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    

    BB BBBBBBBBBBBBBBB
        XXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXXXXXXXXXXX
            X 
        XXXX
    BBBB BBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX
                X 
            XXXXXXXX
        BBBBB
            XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBBB
    BBBBB

XXXXXX
BB BBBBB

XXXX XXXXXXXXXXXXXXXXXXX

BBB BBBB BB BBBBB

XXXX XXXXXXXXXXXXXXXXXX

    BB BBBBBBBBBB
        XXXX XXXXXX XXXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX

        BB BBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB

        XXX XXXXXXXXXXXXXXXXXXX
            
        XXXXX

        XX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFF
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXX
            XXXX XXXX
        XXXX

    XXXXXX

XXXXXX

BBBBBB

XXXXXX

BBBB

XXXX XXXXXXXXXXXXXX
    XXXXXX XXXXX XXXXX XX XXXX XXXXXXXXXXXXXX
XXXXXX

BBBBB

BBBBBBBB