XXXXXXX
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX
        BBBBB BBBBB
            XXXXXX XXX
        BBBBBBBB
    XXXXXXXX

    XXXXXXX
        XX
            XXXXXXXXX
            XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
        X

        XXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXX XX
            XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXX XXXXX
        X

        XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXX
        X

        XXXXXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
        X

        XXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
        X

        XXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
        X

        XXXXXX
            XXXXXXXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX XXXXX
            XXXXXXXXXXXXXXXXXX
        X

        XXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX
            XXXXXXXXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX
        X

        XXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        X
    XXXXXXXX

    BBBBB BBBBBBBBB
    BBBBBBBB
XXXXXXX
XXXXXX

XXXXX
    XX XXXXXXBBB BBBBBBBBBBBXXXXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXX
    BBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXX
    BBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX

    BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXXXX XX
                
            XXXXXX
        BBBBBB
    BBBBB

    BBBBB BBBBBBB
    BBBBBBBB

XXXXXX

BBBBB BBBBBBBB
BBBBBBBB

XXXXXXX
XXXXXXX
XXX
