BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXXXXX

XXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXX
    XXXXXXXXXXX XX
    XXXXXXXXXXXXXXX
X

XXXXXXXXX
    XXXXXXXXXXXXXXXX
X

XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
X

XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXX

    XXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        
    XXXXXX

    XXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
        
    XXXXXX

    BB BBBBBBBBBBBB

        XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
        XXXXXX

        XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            
        XXXXXX

    BBBB

        XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX XXXXXXXXXXXX
        XXXXXX

    BBBBB

    XXXX XXXXXXXXXXXXXXXX


        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX
            XXXXXX XXXXXXXX
        XXXX

    XXXXXX

    BBB BBBB BB BBBBBBBB
       XXXX XXXXXXXXXXXXX
    BB BBBBBBBBBB
        XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBB

    XXXXXXXXX

    XXX
        FFFFFFFFFFFFFFFF
    XXXX

    XXX
        XXXXXXXXXXXXXXXXXXXXXXXX 
    XXXX

    XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXX

    XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBXX
        XXXX XXXX
    XXXX
XXXXXX

BBBBB
XXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXX XXXXX XXXXXXXXX
XXXXXX
    BBBBBB

XXXXXX

BBBBBBBB