BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXXX XXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

    XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
    XX XXXXXXXXXXXXXXXXX
        XXXXXX X XXX XXXXXXXXXXXX XXXXXXX XXX XXXXXX
    XXXX

    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB

        BBB BBBBB BB BBBB
            XXXX XXXXXXXXXXXXXXXXXXX

                XXXXXX XXXXXXX
                    
                XXXXXXXX

                

                BB BBBBBBBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                BBBBB

                BB BBBBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXXXX
                        FFFFFFF F
                    XXXXXXXX
                BBBBB

            XXXXXX
        BBBBBB

        XXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
        XXXXXXXXX

    XXXXXXX

XXXXXX

BBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX

XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
X

XXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX
X

XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXXXX
BBBBBBBB