BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXXXXXXXXX XXXXXX
BBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX

XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
X

XXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
X

XXXXXXX XXX
    XXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXX
    XXXXXXXXXXXXX
X

XXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXX XXXXX XXXXX
X

XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
X

XXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
X

XXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
X

XXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
X

XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
X

XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXX
                 XXXX
            XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXX
                 XXXXX
            XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXX

            XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXX
                XXX XXXXXX
            XXXX

        XXXXXX

        XXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXX XX XXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX

    XXXXXX

XXXXXX

BBBBBBBB